name: formula_ci
# Description: "Moving saphanabootstrap-formula from Travis to Github Actions"
# The CI automatically publishes new releases every time a pull request is merged into master
on:
  push:
    branches:
      - master

#TESTING
#on: push

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install salt-api
      - run: ci/validate-formula.sh

  delivery:
    needs: validation
    runs-on: ubuntu-latest
    container: shap/continuous_deliver
    env:
      FOLDER: package
      PACKAGE_NAME: saphanabootstrap-formula
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
      REVISION: ${{ github.sha }}
      REPOSITORY: ${{ github.repository }}
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - run: sudo /bin/bash -c "sed -i 's~%%VERSION%%~$GITHUB_COMMIT~' _service && sed -i 's~%%REPOSITORY%%~$GITHUB_REPO_SLUG~' _service /scripts/upload.sh"

  submit:
    needs: [validation, delivery]
    runs-on: ubuntu-latest
    container: shap/continuous_deliver

    env:
      PACKAGE_NAME: saphanabootstrap-formula
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
      REVISION: ${{ github.event.release.tag_name }}
      REPOSITORY: ${{ github.repository }}
      TARGET_PROJECT: saphanabootstrap-formula-delivery-step:saphanabootstrap-formula-submit-step
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure OSC
        run: |
          /scripts/init_osc_creds.sh
          mkdir -p $HOME/.config/osc
          cp /root/.config/osc/oscrc $HOME/.config/osc
      - run: exporter-obs-workdir
      - run: exporter-obs-changelog
      - run: exporter-obs-commit
      - run: /scripts/submit.sh
#submit script doesnt have a target project , needs to be fixed
#just a test commit , watch if ci is started :D
# Problem with the submit script TARGET_PROJECT not set. Skipping package submission.
#test push