name: formula_ci

#description: "Moving the formula from travis to Github Actions"
# this is my workflow for the formula

# The Ci automaticaly publishes new releases every time a pull request is merged into master
#on:
#push:
#branches:
#- master

#TESTING
on: push

jobs:
  #every step is a seperate action
  validation:
    runs-on: ubuntu-latest
    steps:
      #Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@master
      - run: |
          apt-get install salt-api
          ci/validate-formula.sh

  delivery:
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

  submit:
    needs: [validation, delivery]
    runs-on: ubuntu-latest
    #need: job  requires the other one to pass the ci process
    steps:
      - uses: actions/checkout@master
