name: formula_ci

#description: "Moving the formula from travis to Github Actions"
# this is my workflow for the formula

# The CI automatically publishes new releases every time a pull request is merged into master
on:
push:
branches:
  - master

#TESTING
#on: push

jobs:
  #every step is a separate action
  validation:
    runs-on: ubuntu-latest
    steps:
      #Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@master
      - run: |
          sudo apt-get install salt-api
          ci/validate-formula.sh

  delivery:
    needs: validation
    runs-on: ubuntu-latest
    container: shap/continuous_deliver
    env:
      FOLDER: package
      PACKAGE_NAME: saphanabootstrap-formula
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
    steps:
      - uses: actions/checkout@master
      - run: |
          sudo /bin/bash -c "sed -i 's~%%VERSION%%~$GITHUB_COMMIT~' _service && sed -i 's~%%REPOSITORY%%~$GITHUB_REPO_SLUG~' _service /scripts/upload.sh"
  submit:
    needs: [validation, delivery]
    runs-on: ubuntu-latest
    container: shap/continuous_deliver
    env:
      PACKAGE_NAME: saphanabootstrap-formula
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
      TARGET_PROJECT:
    steps:
      - uses: actions/checkout@master
      - run: |
          sudo /scripts/submit.sh
