name: formula_ci
# Description: "Moving saphanabootstrap-formula from Travis to Github Actions"
# The CI automatically publishes new releases every time a pull request is merged into master
on:
  push:
    branches:
      - master

#TESTING
#on: push

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install salt-api
      - run: ci/validate-formula.sh

  delivery:
    needs: validation
    runs-on: ubuntu-latest

    container: 
      image: shap/continuous_deliver
      env:
        PACKAGE_NAME: saphanabootstrap-formula
        OBS_USER: ${{ secrets.OBS_USER }}
        OBS_PASS: ${{ secrets.OBS_PASS }}
        OBS_PROJECT: home:Servus007:saphanabootstrap-formula-delivery-step
        REVISION: ${{ github.sha }}
        REPOSITORY: ${{ github.repository }}
        GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSCRC_FILE: /github/home/.config/osc/oscrc

    steps:
      - uses: actions/checkout@v2
      - run:  sudo pwd
      - run:  echo $OSCRC_FILE
      - run:  sed -i 's~%%VERSION%%~$REVISION~' _service 
      - run:  sed -i 's~%%REPOSITORY%%~$REPOSITORY~' _service 
      - run:  pwd;ls -all
      - run:  mkdir -p "$OSCRC_FILE" && cp /root/.config/osc/oscrc "$OSCRC_FILE"
      - run:  pwd;ls -all 
      - run:  /scripts/upload.sh
        



  submit:
    needs: [validation, delivery]
    runs-on: ubuntu-latest
    container: shap/continuous_deliver

    env:
      PACKAGE_NAME: saphanabootstrap-formula
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: home:Servus007:saphanabootstrap-formula-delivery-step
      REVISION: ${{ github.event.release.tag_name }}
      REPOSITORY: ${{ github.repository }}
      TARGET_PROJECT: home:Servus007:saphanabootstrap-formula-delivery-step:saphanabootstrap-formula-submit-step
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -  run: /scripts/submit.sh
      -  run: echo "Finished submbit"
