name: formula_ci

#description: "Moving the formula from travis to Github Actions"
# this is my workflow for the formula

# The CI automaticaly publishes new releases every time a pull request is merged into master
#on:
#push:
#branches:
#- master

#TESTING
on: push

jobs:
  #every step is a seperate action
  validation:
    runs-on: ubuntu-latest
    steps:
      #Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@master
      - run: |
          sudo apt-get install salt-api
          ci/validate-formula.sh

  delivery:
    needs: validation
    runs-on: ubuntu-latest
    steps:
       uses:  actions/checkout@v2
    
      #docker installation
      - run: |
        
          sudo apt update
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt update
          apt-cache policy docker-ce
          sudo apt install docker-ce
       
       
          sudo docker pull shap/continuous_deliver:latest
          docker run -t -v "$(pwd):/package" -w /package -e OBS_USER -e OBS_PASS -e $FOLDER -e OBS_PROJECT -e $PACKAGE_NAME shap/continuous_deliver /bin/bash -c "sed -i 's~%%VERSION%%~$TRAVIS_COMMIT~' _service &&  sed -i 's~%%REPOSITORY%%~$TRAVIS_REPO_SLUG~' _service && /scripts/upload.sh"
        env:
          FOLDER: package
          PACKAGE_NAME: saphanabootstrap-formula

  submit:
    needs: [validation, delivery]
    runs-on: ubuntu-latest
    #need: job  requires the other one to pass the ci process
    steps:
      - uses: actions/checkout@master
