# Description: "Moving saphanabootstrap-formula from Travis to Github Actions"
# The CI automatically publishes new releases every time a pull request is merged into master
name: formula_ci
on:
  push:
    branches:
      - master

env:
  PACKAGE_NAME: habootstrap-formula
#TESTING
#on: push

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -  name: Add salt repository
      - uses: myci-actions/add-deb-repo@4
        with:
          repo: deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2/ bionic main
          key-server: http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub
      - name: install salt
      - run: sudo apt-get install salt-common
      - run: ci/validate-formula.sh

  delivery:
    needs: validation
    runs-on: ubuntu-latest
    container: 
      image: shap/continuous_deliver
      env:
        OBS_USER: ${{ secrets.OBS_USER }}
        OBS_PASS: ${{ secrets.OBS_PASS }}
        OBS_PROJECT: home:Servus007:saphanabootstrap-formula-delivery-step
        REVISION: ${{ github.sha }}
        REPOSITORY: ${{ github.repository }}
        GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSCRC_FILE: /github/home/.config/osc/oscrc
        FOLDER: /package
        PACKAGE_NAME: saphanabootstrap-formula
        

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure OSC   
      - run:  /scripts/init_osc_creds.sh
      - run:  cp /root/.config/osc/oscrc $HOME/.config/osc
      - name: deliver package
      - run:  sed -i 's~%%VERSION%%~${{ github.sha }}~' _service && \
      - run:  sed -i 's~%%REPOSITORY%%~${{ github.repository }}~' _service && \
      - run:  /scripts/upload.sh 
      
        



  submit:
    needs: [validation, delivery]
    runs-on: ubuntu-latest
    container: shap/continuous_deliver

    env:
      PACKAGE_NAME: saphanabootstrap-formula
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: home:Servus007:saphanabootstrap-formula-delivery-step
      REVISION: ${{ github.event.release.tag_name }}
      REPOSITORY: ${{ github.repository }}
      TARGET_PROJECT: home:Servus007:saphanabootstrap-formula-delivery-step:saphanabootstrap-formula-submit-step
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -  run: /scripts/submit.sh
      -  run: echo "Finished submbits"
