name: formula_ci

#description: "Moving the formula from travis to Github Actions"
# this is my workflow for the formula

# The CI automatically publishes new releases every time a pull request is merged into master
#on:
#push:
#branches:
#- master

#TESTING
on: push

jobs:
  #every step is a separate action
  validation:
    runs-on: ubuntu-latest
    steps:
      #Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@master
      - run: |
          sudo apt-get install salt-api
          ci/validate-formula.sh

  delivery:
    needs: validation
    runs-on: ubuntu-latest
    container: shap/continuous_deliver
    env:
      FOLDER: package
      PACKAGE_NAME: saphanabootstrap-formula
      OBS_USER: ${{ secrets.OBS_USER }}
      OBS_PASS: ${{ secrets.OBS_PASS }}
      OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
      steps:
        - uses: actions/checkout@v2
        - name: configure OSC
      run: |
        docker run -t -v "$(pwd):/package" -w /package -e $OBS_USER -e $OBS_PASS -e $FOLDER -e $OBS_PROJECT -e $PACKAGE_NAME 
        shap/continuous_deliver/bin/bash -c "sed -i 's~%%VERSION%%~$TRAVIS_COMMIT~' _service && 
        sed -i 's~%%REPOSITORY%%~$TRAVIS_REPO_SLUG~' _service && 
        /scripts/upload.sh"
  submit:
    needs: [validation, delivery]
    runs-on: ubuntu-latest
    #need: job  requires the other one to pass the ci process
    steps:
      - uses: actions/checkout@master

    env:
      PACKAGE_NAME: saphanabootstrap-formula
